Add unittests for group filtering (Azure)
outlook/oauth2_proxy pull request #1
Opened 2017-02-13 23:52 UTC by pasoroki

2017-02-15 22:56 UTC, thenewwazoo requested changes
Looks really good! I like mocking out the group calls.

2017-02-15 22:56 UTC, thenewwazoo commented on providers/session_state_test.go
> +	assert.Equal(t, 4, strings.Count(encoded, ":"))
Needs a test including a group spec

2017-02-15 22:56 UTC, thenewwazoo commented on providers/provider_data.go
> +	GroupsURL         *url.URL
This type of Group API is unique to Azure, isn't it? I don't think it should live in ProviderData if that's the case.

2017-02-20 20:14 UTC, bdwyertech commented on providers/azure.go
> +	requestUrl := "https://graph.microsoft.com/v1.0/me/memberOf%3F$select=displayName"
Changing the `%3F` here back to a `?` made this all work again.

2017-02-22 23:10 UTC, thenewwazoo commented on providers/session_state_test.go
> +	assert.Equal(t, 4, strings.Count(encoded, ":"))
Should this be 5 now?

2017-02-22 23:11 UTC, thenewwazoo commented on providers/azure.go
> +	requestUrl := "https://graph.microsoft.com/v1.0/me/memberOf%3F$select=displayName"
Hey thanks! Not sure what ate that `?`. @pasoroki, poke this and I'll give it a merge :)

2017-02-22 23:23 UTC, pasoroki commented on providers/session_state_test.go
> +	assert.Equal(t, 4, strings.Count(encoded, ":"))
5 items in `encoded` string, 4 `:` delimiters. Looks fine to me.
The only thing that is missed here is `PermittedGroups` but they are stored in `AzureProvider` structure and shouldn't be visible in `SessionState` so we're good

2017-02-22 23:28 UTC, pasoroki commented on providers/azure.go
> +	requestUrl := "https://graph.microsoft.com/v1.0/me/memberOf%3F$select=displayName"
I confirm, there should be `?` instead of `%3F`

2017-02-22 23:31 UTC, thenewwazoo approved these changes

2017-02-22 23:31 UTC, merged